root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server.exe ./cmd/server"
bin = "./tmp/server.exe"
delay = 1000
exclude_dir = ["tmp", "vendor"]
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = false
include_dir = []
include_ext = ["go", "env"]
kill_delay = "500ms"
log = "build-errors.log"
poll = false
poll_interval = 500
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = true

[log]
main_only = false
silent = false
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
